---
resources:
  - name: resource-tutorial
    type: git
    source:
      uri: https://github.com/EMC-Underground/service_openfaas.git
      branch: master

#params:
#  DNS_SUFFIX: ((dnssuffix))
#  DOCKER_HOST: ((dockerhost))

#inputs:
#  - name: openfaas

jobs:
  - name: job-demo
    public: true
    plan:
      - get: resource-tutorial
      trigger: true

      - task: show-ansible-version
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: bsoper/alpine-ansible
              tag: latest
          run:
            path: ash
            args: ["ansible", "--version"]
