---
resources:
  - name: service-openfaas-repo
    type: git
    source:
      uri: https://github.com/EMC-Underground/service_openfaas.git
      branch: master

jobs:
  - name: job
    public: true
    plan:
      - get: service-openfaas-repo
        trigger: true
      - task: list-files
        config:
          inputs:
            - name: service-openfaas-repo
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          run:
            path: ls
            args: ["-la"]

